# Generated by Django 5.1.2 on 2024-10-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='passagem',
        ),
        migrations.AddField(
            model_name='cliente',
            name='destino',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='horario',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Passagem',
        ),
    ]
