# Generated by Django 5.1.2 on 2024-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SE', 'Segunda'), ('QA', 'Quarta'), ('SA', 'Sabado')], max_length=2)),
                ('destino', models.CharField(choices=[('SP', 'São Paulo'), ('CA', 'Campinas'), ('RI', 'Rio de  Janeiro')], max_length=2)),
                ('horario', models.CharField(choices=[('MA', 'Manhã'), ('TA', 'Tarde'), ('NO', 'Noite')], max_length=2)),
            ],
        ),
    ]
