# Generated by Django 5.1.2 on 2024-10-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='p9',
            field=models.BooleanField(default=False),
        ),
    ]
